services:
  broker:
    image: confluentinc/cp-kafka:7.6.2
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    networks:
      - kafka-network
      - shared-network
    volumes:
      - broker-data-volume:/var/lib/kafka/data
      - broker-config-volume:/etc/kafka
      - broker-secrets-volume:/etc/kafka/secrets
    env_file:
      - ./.kafka.env

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.2
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - 9091:9091
    networks:
      - kafka-network
    volumes:
      - schema-registry-config-volume:/etc/schema-registry
      - schema-registry-secrets-volume:/etc/schema-registry/secrets
    env_file:
      - ./.schema.env

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.6.2
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker
      - schema-registry
    ports:
      - 9021:9021
    networks:
      - kafka-network
    volumes:
      - control-center-data-volume:/var/lib/confluent-control-center
      - control-center-config-volume:/etc/confluent-control-center
    env_file:
      - ./.control.env

volumes:
  broker-data-volume:
    name: broker-data-volume
    driver: local
  broker-config-volume:
    name: broker-config-volume
    driver: local
  broker-secrets-volume:
    name: broker-secrets-volume
    driver: local

  schema-registry-config-volume:
    name: schema-registry-config-volume
    driver: local
  schema-registry-secrets-volume:
    name: schema-registry-secrets-volume
    driver: local

  control-center-data-volume:
    name: control-center-data-volume
    driver: local
  control-center-config-volume:
    name: control-center-config-volume
    driver: local

networks:
  kafka-network:
    name: kafka-network
    driver: bridge
  shared-network:
    name: shared-network
    driver: bridge
